osx_image: xcode9.4
language: objective-c
script:
- set -o pipefail && xcodebuild -scheme "InfiniteScrolelr" -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' ONLY_ACTIVE_ARCH=NO | xcpretty
