osx_image: xcode10.1
language: objective-c
script:
- set -o pipefail && xcodebuild -scheme "InfiniteScroller" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1' ONLY_ACTIVE_ARCH=YES | xcpretty
